import requests

animedb = [
    {
        "title": "Naruto Shippuuden",
        "categories": [
            {"category": "Ação"},
            {"category": "Angústia"},
            {"category": "Comédia"},
            {"category": "Ninja"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/1555/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/1555/large.jpg",
        "original_title": "Naruto: Shippuden",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Pierrot, Studio Pierrot",
        "sinopse": "Já se passaram dois anos e meio desde que Naruto Uzumaki deixou Konohagakure, a Vila Oculta da Folha, para um treinamento intenso após os eventos que alimentaram seu desejo de ser mais forte. Agora a Akatsuki, a misteriosa organização de ninjas desonestos de elite, está se aproximando de seu grande plano que pode ameaçar a segurança de todo o mundo shinobi. ",
    },
    {
        "title": "One Piece",
        "categories": [
            {"category": "Ação"},
            {"category": "Crime"},
            {"category": "Comédia"},
            {"category": "Pirata"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/12/cover_image/21ecb556255bd46b95aea4779d19789f.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/12/large.jpg",
        "original_title": "One Piece",
        "status": "On going",
        "launch_data": "2007-02-15",
        "studio": "Toei Animation",
        "sinopse": "Gol D. Roger era conhecido como o 'Rei dos Piratas', o ser mais forte e mais infame que navegou na Grand Line. A captura e morte de Roger pelo Governo Mundial trouxe uma mudança em todo o mundo. Suas últimas palavras antes de sua morte revelaram a existência do maior tesouro do mundo, One Piece. Foi essa revelação que trouxe a Grande Era dos Piratas, homens que sonhavam em encontrar One Piece - que promete uma quantidade ilimitada de riqueza e fama - e possivelmente o auge da glória e o título de Rei dos Piratas.",
    },
    {
        "title": "Demon Slayer",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Demônio"},
            {"category": "Fantasia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/41370/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/41370/large.jpg",
        "original_title": "Kimetsu no Yaiba",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "ufotable",
        "sinopse": "É o Período Taisho no Japão. Tanjiro, um menino de bom coração que vende carvão para viver, encontra sua família massacrada por um demônio. Para piorar a situação, sua irmã mais nova Nezuko, a única sobrevivente, foi transformada em um demônio. Embora devastado por essa realidade sombria, Tanjiro resolve se tornar um “matador de demônios” para que ele possa transformar sua irmã em humana e matar o demônio que massacrou sua família.",
    },
    {
        "title": "Boku no Hero Academia",
        "categories": [
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Shounen"},
            {"category": "Super-hérois"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11469/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11469/large.jpg",
        "original_title": "Boku no Hero Academia",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "OSSOS, Ossos",
        "sinopse": "Como seria o mundo se 80% da população manifestasse superpoderes extraordinários chamados “Peculiaridades” aos quatro anos? Heróis e vilões estariam lutando em todos os lugares! Tornar-se um herói significaria aprender a usar seu poder, mas onde você iria estudar? Programa Hero da UA High, é claro! Mas o que você faria se fosse um dos 20% que nasceram Quirkless? O estudante do ensino médio Izuku Midoriya quer ser um herói mais do que tudo, mas ele não tem um pingo de poder nele. Sem chance de entrar na prestigiosa UA High School para heróis iniciantes, sua vida está parecendo cada vez mais um beco sem saída. Então, um encontro com All Might, o maior herói de todos, dá a ele a chance de mudar seu destino… (Fonte: Viz Media)",
    },
    {
        "title": "Noragami",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "Super Poderes"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7881/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/7881/large.jpg",
        "original_title": "Noragami",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Bones",
        "sinopse": "Em momentos de necessidade, se você procurar no lugar certo, poderá ver um número de telefone estranho rabiscado em vermelho. Se você ligar para este número, você ouvirá um jovem se apresentar como o Deus Yato. Yato é uma divindade menor e um autoproclamado 'Deus da Entrega', que sonha em ter milhões de adoradores. Sem um único santuário dedicado ao seu nome, no entanto, seus objetivos estão longe de serem realizados. Ele passa seus dias fazendo biscates por cinco ienes cada, até que seu parceiro de armas fica farto de seu mestre inútil e o abandona. Assim como as coisas parecem sombrias para o deus, sua fortuna muda quando uma garota do ensino médio, Hiyori Iki, supostamente salva Yato de um acidente de carro, levando o golpe por ele. Notavelmente, ela sobrevive, mas o evento fez com que sua alma se soltasse e, portanto, pudesse deixar seu corpo. Hiyori exige que Yato a devolva ao normal, mas ao saber que ele precisa de um novo parceiro para fazê-lo, relutantemente concorda em ajudá-lo a encontrar um. E com a ajuda de Hiyori, a sorte de Yato pode finalmente estar mudando.",
    },
    {
        "title": "Avatar: The Last Airbender",
        "categories": [
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Aventura"},
            {"category": "Artes marciais"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7936/original.jpg",
        "image": "https://media.kitsu.io/manga/poster_images/39307/large.jpg",
        "original_title": "Avatar: The Last Airbender",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Nickelodeon Animation Studio",
        "sinopse": "A mania dos desenhos animados de sucesso da Nickelodeon vai para TOKYOPOP, enquanto você revive cada episódio emocionante... agora na forma de cine-mangá fácil de seguir! Em uma busca atemporal que reúne todos os elementos (trocadilho!) da história e cultura asiáticas, Avatar: the Last Airbender tem a mistura perfeita de ação, comédia e aventura! E onde as artes marciais se traduzem em 'levitar-pedras-e-jogá-las-na-cara-do-seu-inimigo', você só quer pular direto e se juntar à escola de karatê local! Não há dúvida de que Avatar: o Último Mestre do Ar ficou rico com fãs em toda a linha, e este editor é apenas um deles! ATLA sacia minha sede por culturas asiáticas geralmente não vistas no mundo da animação, enquanto me atrai ainda mais com magia e ação! E com uma nova mistura de personagens, de um irmão mais velho sarcástico a uma legião de garotas chutando bundas, Continuo voltando! Com apenas duas temporadas concluídas, e quatro completas a serem esperadas, ATLA certamente terá muito mais a oferecer aos seus fãs leais.",
    },
    {
        "title": "Hunter x Hunter",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Drama"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/6448/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/6448/large.jpg",
        "original_title": "Hunter x Hunter",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "MADHOUSE, Madhouse",
        "sinopse": "Hunter x Hunter se passa em um mundo onde os caçadores existem para realizar todo tipo de tarefas perigosas, como capturar criminosos e corajosamente procurar tesouros perdidos em territórios desconhecidos. Gon Freecss, de doze anos, está determinado a se tornar o melhor caçador possível na esperança de encontrar seu pai, que era um caçador e abandonou seu filho há muito tempo. No entanto, Gon logo percebe que o caminho para alcançar seus objetivos é muito mais desafiador do que ele jamais poderia imaginar. Ao longo do caminho para se tornar um caçador oficial, Gon faz amizade com o animado médico em treinamento Leorio, o vingativo Kurapika e o rebelde ex-assassino Killua. Para atingir seus próprios objetivos e desejos, os quatro fazem juntos o Exame Hunter, notório por sua baixa taxa de sucesso e alta probabilidade de morte. Ao longo de sua jornada, Gon e seus amigos embarcam em uma aventura que os coloca em muitas dificuldades e lutas. Eles conhecerão uma infinidade de monstros, criaturas e personagens - enquanto aprendem o que realmente significa ser um caçador.",
    },
    {
        "title": "One Punch Man",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "Ficção científica"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/10740/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/10740/large.jpg",
        "original_title": "One Punch Man",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Madhouse",
        "sinopse": "O aparentemente comum e inexpressivo Saitama tem um hobby bastante único: ser um herói. Para perseguir seu sonho de infância, ele treinou incansavelmente por três anos – e perdeu todo o cabelo no processo. Agora, Saitama é incrivelmente poderoso, tanto que nenhum inimigo é capaz de derrotá-lo em batalha. Na verdade, tudo o que é preciso para derrotar os malfeitores com apenas um soco levou a um problema inesperado - ele não é mais capaz de aproveitar a emoção de lutar e ficou bastante entediado. Isso tudo muda com a chegada de Genos, um ciborgue de 19 anos, que deseja ser discípulo de Saitama depois de ver do que ele é capaz. Genos propõe que os dois se juntem à Associação de Heróis para se tornarem heróis certificados que serão reconhecidos por suas contribuições positivas para a sociedade, e Saitama, chocado por ninguém saber quem ele é, rapidamente concorda. E assim começa a história de One Punch Man, uma comédia de ação que segue um indivíduo excêntrico que deseja lutar contra inimigos fortes que podem lhe dar a emoção que ele sentiu uma vez e talvez, ele se torne popular no processo.",
    },
    {
        "title": "Rascal Does Not Dream of Bunny Girl Senpai",
        "categories": [{"category": "Comédia"}, {"category": "Romance"}],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/41056/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/41056/large.jpg",
        "original_title": "Rascal Does Not Dream of Bunny Girl Senpai",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "CloverWorks",
        "sinopse": "Síndrome da puberdade - Experiências anormais, segundo rumores na internet, são causadas por sensibilidade e instabilidade durante a adolescência. Este ano, Sakuta Azusagawa, estudante do segundo ano de uma escola perto de Enoshima, conhece várias meninas que estão passando por essa 'síndrome da puberdade'. Por exemplo, ele conhece uma coelhinha selvagem na biblioteca. Ela acaba sendo uma atriz em hiato, Mai Sakurajima, que também é sua veterana na escola. Por algum motivo, ninguém mais pode ver essa garota encantadora. ela se tornou invisível…?",
    },
    {
        "title": "Great Teacher Onizuka",
        "categories": [
            {"category": "Comédia"},
            {"category": "Vida escolar"},
            {"category": "Amadurecimento"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/220/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/220/large.jpg",
        "original_title": "Great Teacher Onizuka",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Estúdio Pierrot",
        "sinopse": "Onizuka é um líder de gangue de motoqueiros reformado que está de olho em uma nova e honrosa ambição: se tornar o maior professor do mundo... com o objetivo de conhecer garotas sexy do ensino médio. Ok, então ele é principalmente reformado. No entanto, administradores rigorosos e uma classe de delinquentes implacáveis ​​estão entre Onizuka e seu objetivo e eles usarão qualquer meio, por ilegal ou baixo, para afastar o novo professor. Perfeito, pois os métodos de Onizuka não serão encontrados em nenhum manual de ensino; ele se importa com a diferença entre atividades legais e ilegais tanto quanto se importa com a diferença de idade entre ele e uma garota do ensino médio. Então prepare-se para matemática que não faz sentido, linguagem que você levaria um tapa por usar e biologia que faria um homem adulto corar... a menos, é claro, que você seja o Grande Professor Onizuka.",
    },
    {
        "title": "Ore Monogatari!!",
        "categories": [
            {"category": "Comédia"},
            {"category": "Shoujo"},
            {"category": "Romance"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/10016/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/10016/large.jpg",
        "original_title": "Ore Monogatari!!",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Hospício",
        "sinopse": "Com sua construção muscular e estatura alta, Takeo Gouda não é exatamente um calouro médio do ensino médio. No entanto, por trás de sua aparência intimidadora esconde um coração de ouro, e ele é considerado um herói pelos meninos por sua coragem e cavalheirismo. Infelizmente, essas características não ajudam muito em sua vida amorosa. Como se sua aparência não fosse suficiente para assustar o sexo oposto, o melhor amigo legal e bonito de Takeo e companheiro constante Makoto Sunakawa facilmente rouba os corações das alunas - incluindo todas as garotas que Takeo já gostou. Quando Takeo corajosamente salva a fofa e angelical Rinko Yamato de ser molestada, ele se apaixona por ela instantaneamente, mas suspeita que ela possa estar interessada em Sunakawa. Com seu próprio amor por Yamato continuando a florescer, Takeo desinteressadamente decide agir como seu cupido, mesmo quando ele anseia por sua própria história de amor.",
    },
    {
        "title": "Princess Mononoke",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Passado"},
            {"category": "Samurai"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/142/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/142/large.jpg",
        "original_title": "Mononoke Hime",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Studio Ghibli",
        "sinopse": "Quando uma aldeia Emishi é atacada por um feroz javali demônio, o jovem príncipe Ashitaka coloca sua vida em risco para defender sua tribo. Com seu último suspiro, a fera amaldiçoa o braço do príncipe, concedendo-lhe poderes demoníacos enquanto gradualmente drena sua vida. Instruído pelos anciões da aldeia a viajar para o oeste em busca de uma cura, Ashitaka chega a Tatara, a Cidade de Ferro, onde se vê envolvido em um conflito feroz: Lady Eboshi de Tatara, promovendo o desmatamento constante, se opõe à princesa San e aos espíritos sagrados do floresta, que estão furiosos com a destruição trazida pelos humanos. À medida que as forças opostas da natureza e da humanidade começam a se chocar em uma luta desesperada pela sobrevivência, Ashitaka tenta buscar a harmonia entre os dois, enquanto luta contra o demônio latente dentro dele. Princesa Mononoke é um conto que descreve a conexão entre tecnologia e natureza, enquanto mostra o caminho para a harmonia que pode ser alcançada pela aceitação mútua.",
    },
    {
        "title": "Dragon Ball",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
            {"category": "Comédia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/199/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/199/large.jpg",
        "original_title": "Dragon Ball",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Toei Animation",
        "sinopse": "Gokuu Son é um garoto que vive sozinho na floresta - isto é, até que uma garota chamada Bulma o encontra em sua busca por um conjunto de objetos mágicos chamados 'Dragon Balls'. Como dizem que os artefatos concedem um desejo a quem coletar todos os sete, Bulma espera reuni-los e desejar um namorado perfeito. Gokuu está de posse de uma esfera do dragão, mas infelizmente para Bulma, ele se recusa a se separar dela, então ela faz um acordo com ele: ele pode acompanhá-la em sua jornada se ele a deixar emprestar o poder da esfera do dragão. Com isso, os dois partiram na jornada de uma vida. Eles não vão na jornada sozinhos. No caminho, eles encontram o velho Muten-Roshi e aspirante a discípulo Kuririn, com quem Gokuu treina para se tornar um artista marcial mais forte para o próximo Torneio Mundial de Artes Marciais. No entanto' nem tudo é diversão e jogos; a capacidade de realizar qualquer desejo é poderosa, e há outras que fariam muito pior do que apenas desejar um namorado. Para impedir aqueles que tentam abusar do poder lendário, eles treinam para se tornarem lutadores mais fortes, usando sua força recém-descoberta para ajudar as pessoas ao seu redor ao longo do caminho.",
    },
    {
        "title": "Attack on Titan",
        "categories": [
            {"category": "Ação"},
            {"category": "Drama"},
            {"category": "Violência"},
            {"category": "Drama"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7442/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/7442/large.jpg",
        "original_title": "Shingeki no Kyojin",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Wit Studio",
        "sinopse": "Séculos atrás, a humanidade foi massacrada até quase a extinção por monstruosas criaturas humanóides chamadas titãs, forçando os humanos a se esconderem com medo atrás de enormes paredes concêntricas. O que torna esses gigantes realmente aterrorizantes é que seu gosto pela carne humana não nasce da fome, mas do que parece ser do prazer. Para garantir sua sobrevivência, os remanescentes da humanidade começaram a viver dentro de barreiras defensivas, resultando em cem anos sem um único encontro de titãs. No entanto, essa calma frágil é logo quebrada quando um titã colossal consegue romper a parede externa supostamente inexpugnável, reacendendo a luta pela sobrevivência contra as abominações antropófagas. Depois de testemunhar uma terrível perda pessoal nas mãos das criaturas invasoras, Eren Yeager dedica sua vida à sua erradicação, alistando-se no Survey Corps, uma unidade militar de elite que combate os impiedosos humanóides fora da proteção das muralhas. Baseado no premiado mangá de Hajime Isayama, Shingeki no Kyojin segue Eren, junto com sua irmã adotiva Mikasa Ackerman e seu amigo de infância Armin Arlert, enquanto eles se juntam à guerra brutal contra os titãs e correm para descobrir uma maneira de derrotá-los antes do último fim. paredes são quebradas.",
    },
    {
        "title": "Kuroko no Basket",
        "categories": [
            {"category": "Comédia"},
            {"category": "Esportes"},
            {"category": "Amizade"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/6595/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/6595/large.jpg",
        "original_title": "Kuroko no Basket",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Produção IG",
        "sinopse": "A equipe de basquete da Teikou Junior High School é coroada campeã três anos consecutivos graças a cinco jogadores excepcionais que, com suas habilidades únicas e de tirar o fôlego, deixam os adversários em desespero e os fãs em admiração. No entanto, depois de se formar, esses companheiros de equipe, conhecidos como 'A Geração dos Milagres', seguem caminhos separados e agora se consideram rivais. Na Seirin High School, dois calouros recém-recrutados provam que não são jogadores de basquete comuns: Taiga Kagami, um jogador promissor que retorna dos EUA, e Tetsuya Kuroko, um estudante aparentemente comum cuja falta de presença permite que ele se mova despercebido. Embora Kuroko não seja atlético nem capaz de marcar pontos, ele foi membro do time de basquete de Teikou, onde jogou como o 'Sexto Homem Fantasma'. que facilmente passou a bola e ajudou seus companheiros de equipe. Kuroko no Basket segue a jornada dos jogadores de Seirin enquanto eles tentam se tornar o melhor time japonês do ensino médio ao vencer o Campeonato Interhigh. Para alcançar seu objetivo, eles precisam cruzar caminhos com várias equipes poderosas, algumas das quais têm um dos cinco jogadores com habilidades divinas, a quem Kuroko e Taiga fazem um pacto para derrotar.",
    },
    {
        "title": "Soul Eater",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/3128/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/3128/large.jpg",
        "original_title": "Soul Eater",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Bones",
        "sinopse": "Death City é o lar da famosa Shibusen, uma academia técnica liderada pelo próprio Shinigami-Lord Death. Sua missão: levantar 'Death Scythes' para o Shinigami usar contra os muitos males de seu mundo fantástico. Essas foices da morte, no entanto, não são feitas de armas físicas; em vez disso, eles nascem de híbridos humanos que têm a capacidade de transformar seus corpos em Armas Demoníacas, e somente depois de consumirem as almas de 99 seres malignos e a alma de uma bruxa. Soul Eater Evans, um Demon Scythe que só parece se importar com o que é legal, pretende se tornar um Death Scythe com a ajuda de seu portador, ou meister, Maka Albarn. A dupla contrastante trabalha e estuda ao lado do Black☆Star de cabeça quente e sua arma carinhosa Tsubaki, bem como o próprio filho do Shinigami, Death the Kid, um portador duplo obsessivo-compulsivo de pistolas gêmeas Patty e Liz.Soul Eater segue esses estudantes de Shibusen enquanto eles assumem missões para coletar almas e proteger a cidade das ameaças do mundo enquanto trabalham juntos sob o sol risonho para se tornarem mais sãos em mente e corpo , e alma.",
    },
    {
        "title": "Code Geass: Lelouch of the Rebellion R2",
        "categories": [
            {"category": "Ação"},
            {"category": "Drama"},
            {"category": "Futuro"},
            {"category": "Guerra"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/2634/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/2634/large.jpg",
        "original_title": "Code Geass: Hangyaku no Lelouch R2",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Sunrise",
        "sinopse": "Um ano se passou desde a Rebelião Negra, uma revolta fracassada contra o Sacro Império Britânico liderado pelo vigilante mascarado Zero, que agora está desaparecido. Perdendo sem seu líder revolucionário, o grupo de resistência da Área 11 - os Cavaleiros Negros - encontram-se impotentes demais para combater a brutalidade infligida aos Onze pela Britannia, que aumentou significativamente para esmagar qualquer esperança de uma futura revolta. Lelouch Lamperouge, tendo perdido toda a memória de sua vida dupla, vive pacificamente ao lado de seus amigos como estudante do ensino médio na Ashford Academy. Sua ex-parceira CC, incapaz de aceitar essa reviravolta, se encarrega de lembrá-lo de seu propósito passado, esperando que o mentor Zero ressuscite mais uma vez para terminar o que começou, nesta emocionante conclusão da série.",
    },
    {
        "title": "Yagate Kimi ni Naru",
        "categories": [{"category": "Romance"}, {"category": "Shoujo Ai"}],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/41240/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/41240/large.jpg",
        "original_title": "Yagate Kimi ni Naru",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "TROYCA",
        "sinopse": "Yuu sempre sonhou em receber uma confissão de amor, mas não sente nada quando um garoto lhe dá uma. Confusa, ela começa seu primeiro ano do ensino médio e conhece a bela presidente do conselho estudantil, Nanami, que faz seu coração disparar.",
    },
    {
        "title": "Mairimashita! Iruma-kun",
        "categories": [
            {"category": "Shounen"},
            {"category": "Comédia"},
            {"category": "Demônio"},
            {"category": "Fantasia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/42310/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/42310/large.jpg",
        "original_title": "Mairimashita! Iruma-kun",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Bandai Namco Pictures",
        "sinopse": "A vida caótica de um menino em um internato 'prestigioso' para demônios de elite! Iruma Suzuki, humano, 14 anos, um dia se vê vendido ao diabo. Para aumentar sua situação, seu dono amoroso e autonomeado 'Vovô' é o diretor de sua nova escola. Agora Iruma deve lidar com um estudante arrogante que o desafia para um duelo, uma garota com problemas de adaptação e tantos outros seres assustadores! Este pacifista supremo pode evitar as fundas e flechas que são lançadas em seu caminho? Enquanto ele luta freneticamente, a bondade inata de Iruma começa a conquistar os inimigos.",
    },
    {
        "title": "Black Clover",
        "categories": [
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Shounen"},
            {"category": "Fantasia"},
            {"category": "Mágica"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/13209/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/13209/large.jpg",
        "original_title": "Black Clover",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Studio Pierrot",
        "sinopse": "Em um mundo onde a magia é tudo, Asta e Yuno são encontrados abandonados em uma igreja no mesmo dia. Enquanto Yuno é dotado de poderes mágicos excepcionais, Asta é o único neste mundo sem nenhum. Aos quinze anos, ambos recebem grimórios, livros mágicos que amplificam a magia de seu portador. O de Asta é um raro Grimório de Anti-Magia que nega e repele os feitiços de seu oponente. Sendo opostos, mas bons rivais, Yuno e Asta estão prontos para o mais difícil dos desafios para alcançar seu sonho comum: ser o Rei Mago. Desistir nunca é uma opção!",
    },
    {
        "title": "Jujutsu Kaisen",
        "categories": [
            {"category": "Ação"},
            {"category": "Demônio"},
            {"category": "Shounen"},
            {"category": "Angústia"},
            {"category": "Violência"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/42765/original.jpeg",
        "image": "https://media.kitsu.io/anime/poster_images/42765/large.jpg",
        "original_title": "Jujutsu Kaisen",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "MAPPA",
        "sinopse": "Yuji Itadori é um menino com uma força física tremenda, embora viva uma vida escolar completamente normal. Um dia, para salvar um colega de classe que foi atacado por maldições, ele come o dedo de Ryomen Sukuna, levando a maldição para dentro de sua própria alma. A partir de então, ele compartilha um corpo com Ryomen Sukuna. Guiado pelo mais poderoso dos feiticeiros, Satoru Gojo, Itadori é admitido na Tokyo Jujutsu High School, uma organização que luta contra as maldições... que ele nunca poderia voltar atrás.",
    },
    {
        "title": "Koi to Uso",
        "categories": [
            {"category": "Drama"},
            {"category": "Romance"},
            {"category": "Vida escolar"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/13257/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/13257/large.jpg",
        "original_title": "Koi to Uso",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "LIDENFILMS, LIDENFILMS",
        "sinopse": "Mentiras são proibidas e o amor é duplamente proibido. Em um futuro próximo, quando os jovens no Japão completam dezesseis anos, eles recebem um parceiro de casamento pelo governo. As pessoas não precisam se dar ao trabalho de procurar alguém, e todos aceitam que o país encontrará um parceiro compatível para fazê-los felizes. Yukari Nejima tem quinze anos. Ele mora em um pequeno canto do país, e simplesmente não consegue progredir na vida. Tanto academicamente quanto atleticamente, ele está abaixo da média. Mas dentro dele, ele esconde um coração ardendo de paixão! Neste mundo em que o amor é proibido, o que acontecerá com ele quando se apaixonar?",
    },
    {
        "title": "Kumo desu ga, Nani ka?",
        "categories": [
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "Fantasia"},
            {"category": "isekai"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/manga/cover_images/37173/original.jpg",
        "image": "https://media.kitsu.io/manga/poster_images/37173/large.jpg",
        "original_title": "Kumo desu ga, Nani ka?",
        "status": "On going",
        "launch_data": "2007-02-15",
        "studio": " Millepensee",
        "sinopse": "Quando uma misteriosa explosão matou uma turma inteira cheia de alunos do ensino médio, as almas de todos na sala foram transportadas para um mundo de fantasia e reencarnadas. Enquanto alguns alunos reencarnaram como príncipes ou prodígios, outros não foram tão abençoados. Nossa heroína, que era a mais baixa da turma, descobriu que reencarnou como uma aranha!? Agora na parte inferior da cadeia alimentar, ela precisa se adaptar à situação atual com força de vontade para viver! Preso em um labirinto perigoso cheio de monstros, é comer ou ser comido! Esta é a história de uma aranha fazendo tudo o que pode para sobreviver!",
    },
    {
        "title": "Burn the Witch",
        "categories": [
            {"category": "Ação"},
            {"category": "Fantasia"},
            {"category": "Magia"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/43146/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/43146/large.jpg",
        "original_title": "Burn the Witch",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Studio Colorido",
        "sinopse": "Historicamente, 72% de todas as mortes em Londres estão relacionadas a dragões, seres fantásticos invisíveis para a maioria das pessoas. Embora desconhecido para a maioria, algumas pessoas têm enfrentado esses dragões. Apenas os habitantes de Reverse London que vivem no lado oculto de Londres podem ver os dragões. Mesmo assim, apenas alguns selecionados se qualificam o suficiente como bruxas ou bruxos para fazer contato direto com eles. Os protagonistas da história são a dupla de bruxas Noel Niihashi e Ninny Spangcole. Eles são agentes de proteção para Wing Bind (WB), uma organização para conservação e gestão de dragões. Sua missão é proteger e gerenciar os dragões dentro de Londres em nome do povo.",
    },
    {
        "title": "Bungou Stray Dogs",
        "categories": [
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Crime"},
            {"category": "Mistério"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11339/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11339/large.jpg",
        "original_title": "Bungou Stray Dogs",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "BONES, Bones",
        "sinopse": "Durante semanas, o orfanato de Atsushi Nakajima foi atormentado por um tigre místico que só ele parece conhecer. Suspeito de estar por trás dos estranhos incidentes, o jovem de 18 anos é abruptamente expulso do orfanato e deixado com fome, sem teto e vagando pela cidade. Enquanto passava fome na margem de um rio, Atsushi salva um homem bastante excêntrico chamado Osamu Dazai de se afogar. Entusiasta do suicídio e detetive sobrenatural, Dazai está investigando o mesmo tigre que aterroriza o menino. Juntamente com o parceiro de Dazai, Doppo Kunikida, eles resolvem o mistério, mas sua resolução deixa Atsushi em apuros. À medida que vários eventos estranhos acontecem, Atsushi é coagido a se juntar à empresa de investigadores sobrenaturais, assumindo casos incomuns que a polícia não pode lidar, ao lado de seus numerosos colegas de trabalho enigmáticos.",
    },
    {
        "title": "Yakusoku no Neverland",
        "categories": [
            {"category": "Horror"},
            {"category": "Mistério"},
            {"category": "Shounen"},
            {"category": "Ação"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/41312/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/41312/large.jpg",
        "original_title": "Yakusoku no Neverland",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "CloverWorks",
        "sinopse": "Os órfãos da Grace Field House só conheceram a paz. Sua casa é agradável, suas barrigas ficam cheias e sua cuidadora, mamãe, os ama muito. Mas o mundo deles vira de cabeça para baixo quando as crianças mais inteligentes do grupo – Emma, ​​Ray e Norman – descobrem o horror que os espera no dia da adoção. Agora, sua inteligência cultivada pode ser sua única chance de sobrevivência.",
    },
    {
        "title": "Tokyo Ghoul",
        "categories": [
            {"category": "Ação"},
            {"category": "Horror"},
            {"category": "Violência"},
            {"category": "Mistério"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/8271/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/8271/large.jpg",
        "original_title": "Tokyo Ghoul",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Studio Pierrot, Pierrot Plus",
        "sinopse": "Tóquio se tornou uma cidade cruel e impiedosa – um lugar onde criaturas cruéis chamadas “ghouls” coexistem ao lado de humanos. Os cidadãos desta outrora grande metrópole vivem com medo constante desses selvagens sanguinários e sua sede de carne humana. No entanto, a maior ameaça que esses ghouls representam é sua capacidade perigosa de se disfarçar de humanos e se misturar com a sociedade. Baseado no mangá de terror sobrenatural de Sui Ishida, Tokyo Ghoul segue Ken Kaneki, um estudante universitário tímido e estudioso, que é instantaneamente atraído por Rize Kamishiro, um ávido leitor como ele. No entanto, Rize não é exatamente quem ela parece, e esse encontro infeliz empurra Kaneki para as profundezas sombrias do mundo desumano dos ghouls. Em uma reviravolta do destino, Kaneki é salvo pela enigmática garçonete Touka Kirishima, e assim começa seu novo, vida secreta como um meio-ghoul/meio-humano que deve encontrar uma maneira de se integrar em ambas as sociedades. ",
    },
    {
        "title": "Bungo Stray Dogs",
        "categories": [
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Crime"},
            {"category": "Mistério"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11339/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11339/large.jpg",
        "original_title": "Bungo Stray Dogs",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "BONES, Bones",
        "sinopse": "Durante semanas, o orfanato de Atsushi Nakajima foi atormentado por um tigre místico que só ele parece conhecer. Suspeito de estar por trás dos estranhos incidentes, o jovem de 18 anos é abruptamente expulso do orfanato e deixado com fome, sem teto e vagando pela cidade. Enquanto passava fome na margem do rio, Atsushi salva um homem bastante excêntrico chamado Osamu Dazai de se afogar. Entusiasta do suicídio e detetive sobrenatural, Dazai está investigando o mesmo tigre que aterroriza o menino. Juntamente com o parceiro de Dazai, Doppo Kunikida, eles resolvem o mistério, mas sua resolução deixa Atsushi em apuros. À medida que vários eventos estranhos acontecem, Atsushi é coagido a se juntar à empresa de investigadores sobrenaturais, assumindo casos incomuns que a polícia não pode lidar, ao lado de seus numerosos colegas de trabalho enigmáticos.",
    },
    {
        "title": "Kiznaiver",
        "categories": [{"category": "Ficção científica"}, {"category": "Romance"}],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11437/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11437/large.jpg",
        "original_title": "Kiznaiver",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Trigger",
        "sinopse": "A história se passa em Sugomori, uma cidade construída sobre terras recuperadas que uma vez prosperou como uma cidade futurista. Um garoto do ensino médio que mora lá, Agata Katsuhira, de alguma forma é incapaz de sentir qualquer dor. Um dia antes do início das férias de verão, Katsuhira é chamada por uma misteriosa garota chamada Sonozaki Noriko e escolhida para se tornar parte de um grupo de pessoas que compartilham a dor umas das outras: uma 'Kiznaiver'. Vários de seus colegas de classe também foram escolhidos como parte desse grupo, mas são todos pessoas de diferentes círculos que normalmente não se associariam.",
    },
    {
        "title": "No Game No Life",
        "categories": [
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "isekai"},
            {"category": "Fantasia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7880/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/7880/large.jpg",
        "original_title": "No Game No Life",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "MADHOUSE, Madhouse",
        "sinopse": "No Game No Life é uma comédia surreal que segue Sora e Shiro, irmãos NEET fechados e a dupla de jogadores online por trás do lendário nome de usuário 'Kuuhaku'. Eles vêem o mundo real como apenas mais um jogo ruim; no entanto, um estranho e-mail desafiando-os para uma partida de xadrez muda tudo - o irmão e a irmã são mergulhados em um reino sobrenatural onde conhecem Tet, o Deus dos Jogos. O misterioso deus dá as boas-vindas a Sora e Shiro em Disboard, um mundo onde todas as formas de conflito – desde pequenas disputas até o destino de países inteiros – são resolvidas não por meio de guerra, mas por meio de jogos de alto risco. Este sistema funciona graças a uma regra fundamental em que cada parte deve apostar algo que considere de igual valor à aposta da outra parte. Nesta terra estranha onde a própria ideia de humanidade é reduzida a brincadeira de criança, A dupla de jogadores geniais e indiferentes de Sora e Shiro finalmente encontrou um motivo real para continuar jogando: unir as dezesseis raças de Disboard, derrotar Tet e se tornar os deuses deste novo mundo do jogo-é-tudo. ",
    },
    {
        "title": "Ao no Exorcist",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Comédia"},
            {"category": "Drama"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/5940/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/5940/large.jpg",
        "original_title": "Ao no Exorcist",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "A-1 Fotos",
        "sinopse": "Humanos e demônios são dois lados da mesma moeda, assim como Assiah e Gehenna, seus respectivos mundos. A única maneira de viajar entre os reinos é por meio de possessão, como nas histórias de fantasmas. No entanto, Satanás, o governante da Gehenna, não consegue encontrar um hospedeiro adequado para possuir e, portanto, permanece preso em seu mundo. Em uma tentativa desesperada de conquistar Assiah, ele envia seu filho, com a intenção de que ele eventualmente se torne um recipiente capaz de ser possuído pelo rei demônio. Ao no Exorcist segue Rin Okumura, que parece ser um adolescente comum e um tanto problemático - isto é até que um dia ele é emboscado por demônios. Seu mundo vira de cabeça para baixo quando ele descobre que ele é de fato o próprio filho de Satanás e que seu pai demônio deseja que ele retorne para que eles possam conquistar Assiah juntos. Não querendo se juntar ao rei da Geena, Rin decide começar a treinar para se tornar um exorcista para que ele possa lutar para defender Assiah ao lado de seu irmão Yukio.",
    },
    {
        "title": "JoJo's Bizarre Adventure: Stone Ocean",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/44294/cover_image/7199329cbdcaa6af51cf23a13d1f756e.png",
        "image": "https://media.kitsu.io/anime/poster_images/44294/large.jpg",
        "original_title": "JoJo no Kimyou na Bouken: Stone Ocean",
        "status": "On going",
        "launch_data": "2007-02-15",
        "studio": "Netflix",
        "sinopse": "O legado da família Joestar continua com Jolyne enquanto ela e seus companheiros assumem novos usuários de Stand atrás das grades da Green Dolphin Street Prison.",
    },
    {
        "title": "The Rising of the Shield Hero",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Seinen"},
            {"category": "Isekai"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/13593/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/13593/large.jpg",
        "original_title": "Tate no Yuusha no Nariagari",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Kinema Citrus",
        "sinopse": "Iwatani Naofumi, um otaku comum, encontra um livro na biblioteca que o convoca para outro mundo. Ele é encarregado de juntar a espada, a lança e o arco como um dos Quatro Heróis Cardeais e lutar contra as Ondas da Catástrofe como o Herói do Escudo. Animado com a perspectiva de uma grande aventura, Naofumi sai com seu grupo. No entanto, apenas alguns dias depois, ele é traído e perde todo o seu dinheiro, dignidade e respeito. Incapaz de confiar em mais ninguém, ele emprega uma escrava chamada Raphtalia e enfrenta as Ondas e o mundo. Mas ele realmente encontrará uma maneira de reverter essa situação desesperadora?",
    },
    {
        "title": "The Devil is a Part-Timer!",
        "categories": [
            {"category": "Comédia"},
            {"category": "Fantasia"},
            {"category": "Romance"},
            {"category": "Isekai"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7314/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/7314/large.jpg",
        "original_title": "Hataraku Maou-sama!",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "White Fox",
        "sinopse": "Causando medo nos corações dos mortais, o Demon Lord Satan começa a conquistar a terra de Ente Isla com seus vastos exércitos de demônios. No entanto, enquanto embarca nessa busca brutal para dominar o continente, seus esforços são frustrados pela heroína Emilia, forçando Satanás a fazer sua rápida retirada através de um portal dimensional apenas para pousar no mundo humano. Junto com seu leal general Alsiel, o demônio se encontra preso na Tóquio moderna e promete retornar e completar sua subjugação de Ente Isla - isto é, se eles puderem encontrar um caminho de volta! Impotente em um mundo sem magia, Satanás assume o disfarce de um humano chamado Sadao Maou e começa a trabalhar no MgRonald's - um restaurante local de fast-food - para sobreviver. ",
    },
    {
        "title": "Neon Genesis Evangelion",
        "categories": [
            {"category": "Mecha"},
            {"category": "Ação"},
            {"category": "Violência"},
            {"category": "Ficção"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/21/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/21/large.jpg",
        "original_title": "Shinseiki Evangelion",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "GAINAX, Tatsunoko Production",
        "sinopse": "No ano de 2015, o mundo está à beira da destruição. A última esperança da humanidade está nas mãos da Nerv, uma agência especial sob as Nações Unidas, e seus Evangelions, máquinas gigantes capazes de derrotar os Anjos que anunciam a ruína da Terra. Gendou Ikari, chefe da organização, procura pilotos compatíveis que possam se sincronizar com os Evangelions e realizar seu verdadeiro potencial. Ajudando neste esforço defensivo estão os talentosos funcionários Misato Katsuragi, Chefe de Operações Táticas, e Ritsuko Akagi, Cientista Chefe. Cara a cara com seu pai pela primeira vez em anos, a vida média de Shinji Ikari, de 14 anos, muda irreversivelmente quando ele é levado para as profundezas da Nerv e para um novo destino angustiante - ele deve se tornar o piloto de Evangelion Unidade-01 com o destino da humanidade em seus ombros. ",
    },
    {
        "title": "Akame ga Kill!",
        "categories": [
            {"category": "Aventura"},
            {"category": "Ação"},
            {"category": "Violência"},
            {"category": "Drama"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/8270/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/8270/large.jpg",
        "original_title": "アカメが斬る！",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "White Fox",
        "sinopse": "Sob o domínio de um império tirânico, Tatsumi, um jovem espadachim, deixa sua casa para salvar sua aldeia atingida pela pobreza. Ele conhece uma garota chamada Akame, uma assassina que foi comprada, submetida a lavagem cerebral e treinada para matar pelo Império. Akame é um membro do grupo secreto de assassinos chamado “Night Raid” que usa armas especiais chamadas Teigu. Juntos, Tatsumi e os membros do Night Raid enfrentam o império corrupto.",
    },
    {
        "title": "Fairy Tail!",
        "categories": [
            {"category": "Magia"},
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Ecchi"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/4676/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/4676/large.jpg",
        "original_title": "フェアリーテイル",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Satelight, A-1 Pictures",
        "sinopse": "Uma maga celestial superficial, mas de bom coração, Lucy Heartfilia, se junta a uma famosa guilda de bruxos em Magnolia Town chamada Fairy Tail, onde os membros usam seus poderes para ganhar recompensas em troca de cumprir missões. Aqui ela faz amizade com um impetuoso, mas fiel mago matador de dragões, Natsu Dragneel, que está vasculhando a terra em busca de seu pai desaparecido. Os dois formam um vínculo com os magos Erza Scarlet e Gray Fullbuster, e juntos eles enfrentam desafios assustadores, enfrentando vários aliados e inimigos poderosos ao longo do caminho. Criado por Hiro Mashima, Fairy Tail é uma aventura repleta de ação que segue Lucy e seus amigos enquanto aprendem o valor da amizade, do perdão e da família.",
    },
    {
        "title": "Dorohedoro",
        "categories": [
            {"category": "Magia"},
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Seinei"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/42040/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/42040/large.jpg",
        "original_title": "ドロヘドロ",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " MAPPA",
        "sinopse": "Buraco - um bairro escuro, decrépito e desordenado onde os fortes atacam os fracos e a morte é uma ocorrência comum - é quase condizente com o nome dado a ele. Um reino separado da lei e da ética, é um campo de testes para os usuários de magia que o dominam. Como uma raça que ocupa os degraus mais altos de sua sociedade, os usuários de magia pensam nos habitantes de Hole como nada mais do que insetos. Assassinados, mutilados e feitos experimentos sem pensar duas vezes, os impotentes moradores de Hole enchem os corredores do hospital de Hole diariamente. Possuindo acesso livre de e para a fossa, e com pouco desafio à sua autoridade, os usuários de magia parecem indomáveis ​​para a maioria - exceto para alguns. Kaiman, mais réptil que o homem, é um desses indivíduos. Ele os caça em uma busca imprudente por respostas com apenas um par de baionetas confiável e sua imunidade à magia. Amaldiçoado por sua aparência e atormentado por pesadelos, os usuários de magia são sua única pista para restaurar sua vida ao normal. ",
    },
    {
        "title": "Toradora!",
        "categories": [
            {"category": "Comédia"},
            {"category": "Ação"},
            {"category": "Romance"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/3532/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/3532/large.jpg",
        "original_title": "とらドラ！",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " J.C.Staff",
        "sinopse": "Ryuuji Takasu é um estudante do ensino médio gentil com amor pelo trabalho doméstico; mas em contraste com sua natureza gentil, ele tem um rosto intimidador que muitas vezes o rotula como delinquente. Por outro lado, está Taiga Aisaka, uma estudante pequena e parecida com uma boneca, que é tudo menos uma garota fofa e frágil. Equipado com uma katana de madeira e personalidade agressiva, Taiga é conhecido em toda a escola como o 'Tigre de Palma'. Um dia, um erro embaraçoso faz com que os dois alunos se cruzem. Ryuuji descobre que Taiga realmente tem um lado doce: ela tem uma queda pelo popular vice-presidente, Yuusaku Kitamura, que por acaso é seu melhor amigo.",
    },
    {
        "title": "Durarara!!",
        "categories": [
            {"category": "Crime"},
            {"category": "Drama"},
            {"category": "Ação"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/4696/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/4696/large.jpg",
        "original_title": "デュラララ!!",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Brain's Base",
        "sinopse": "No distrito de Ikebukuro, no centro de Tóquio, em meio a muitos rumores estranhos e avisos de gangues anônimas e ocupantes perigosos, uma lenda urbana se destaca acima do resto - a existência de um 'Black Rider' sem cabeça que é visto dirigindo uma motocicleta preta. pelas ruas da cidade. Mikado Ryuugamine sempre desejou a agitação da vida na cidade, e um convite de um amigo de infância o convence a se mudar para Tóquio. Testemunhando o Cavaleiro Negro em seu primeiro dia na cidade, seus desejos já parecem ter sido atendidos. Mas à medida que eventos sobrenaturais começam a ocorrer, cidadãos comuns como ele, junto com os habitantes mais coloridos de Ikebukuro, estão envolvidos na comoção que estoura em sua cidade. ",
    },
    {
        "title": "IS: Infinite Stratos",
        "categories": [
            {"category": "Mecha"},
            {"category": "Romance"},
            {"category": "Comédia"},
            {"category": "Ação"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/5583/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/5583/large.jpg",
        "original_title": "Infinite Stratos",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " 8 bits",
        "sinopse": "O Japão projetou um exoesqueleto armado 'Infinite Stratos' (IS) e tornou-se o mainstream das armas. Como apenas as mulheres podem operar o SI, as mulheres dominam a sociedade sobre os homens. Orimura Ichika é um garoto de 15 anos e acidentalmente toca um IS colocado na escola de treinamento de pilotos do IS. Ele é considerado o único homem que pode operar o EI e forçado a entrar na escola de treinamento. A agitada vida escolar de Ichika cercada por garotas começou.",
    },
    {
        "title": "Teasing Master Takagi-san",
        "categories": [
            {"category": "Shounen"},
            {"category": "Romance"},
            {"category": "Comédia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/13635/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/13635/large.jpg",
        "original_title": "Karakai Jouzu no Takagi-san",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Shin-Ei Animation",
        "sinopse": "Cansado de ser impiedosamente provocado por seu colega Takagi, Nishikata prometeu recuperá-la e provocar com sucesso a garota que o fez corar inúmeras vezes. Afinal, se você corar, você perde! Mas obter vingança não é tão fácil quando todas as tentativas explodem em seu rosto. Nishikata fará Takagi corar ou ganhará algo mais gratificante com suas tentativas desajeitadas?",
    },
    {
        "title": "A Silent Voice",
        "categories": [
            {"category": "Amizade"},
            {"category": "Romance"},
            {"category": "Drama"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/10028/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/10028/large.jpg",
        "original_title": "Koe no Katachi",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Kyoto Animation",
        "sinopse": "Shoya é um valentão. Quando Shoko, uma garota que não pode ouvir, entra em sua classe do ensino fundamental, ela se torna seu alvo favorito, e Shoya e seus amigos se instigam a inventar novas torturas para ela. Mas a crueldade das crianças vai longe demais. Shoko é forçado a deixar a escola, e Shoya acaba assumindo toda a culpa. Seis anos depois, os dois se reencontram. Shoya pode compensar seus erros do passado, ou é tarde demais?",
    },
    {
        "title": "Saiki Kusuo no Psi-nan",
        "categories": [
            {"category": "Comédia"},
            {"category": "Humor"},
            {"category": "Vida Escolar"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/12127/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/12127/large.jpg",
        "original_title": "Saiki Kusuo no Ψ-nan",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Funimation",
        "sinopse": "Para a pessoa comum, as habilidades psíquicas podem parecer uma bênção; para Kusuo Saiki, no entanto, isso não poderia estar mais longe da verdade. Dotado de uma grande variedade de habilidades sobrenaturais que vão desde a telepatia até a visão de raio-x, ele acha que essa chamada bênção não passa de uma maldição. Como todos os inconvenientes que seus poderes causam se acumulam constantemente, tudo o que Kusuo almeja é uma vida comum e sem problemas - uma vida onde a ignorância é uma benção.",
    },
    {
        "title": "Food Wars",
        "categories": [
            {"category": "Comédia"},
            {"category": "Shounen"},
            {"category": "Culinaria"},
            {"category": "Ecchi"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/9967/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/9967/large.jpg",
        "original_title": "Shokugeki no Soma",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "J.C.Staff",
        "sinopse": "Desde criança, Souma Yukihira, de quinze anos, ajuda seu pai trabalhando como sous chef no restaurante que seu pai administra e possui. Ao longo dos anos, Souma desenvolveu uma paixão por entreter seus clientes com suas criações culinárias criativas, habilidosas e ousadas. Seu sonho é um dia ser dono do restaurante de sua família como chefe de cozinha. No entanto, quando seu pai de repente decide fechar o restaurante para testar suas habilidades culinárias em restaurantes ao redor do mundo, ele envia Souma para a Tootsuki Culinary Academy, uma escola de culinária de elite onde apenas 10% dos alunos se formam. A instituição é famosa por seus 'Shokugeki' ou 'guerras de comida', onde os alunos se enfrentam em confrontos culinários intensos e de alto risco. Enquanto Souma e seus novos colegas de escola lutam para sobreviver ao estilo de vida extremo de Tootsuki, mais e maiores desafios o aguardam, colocando à prova seus anos de aprendizado sob o comando de seu pai.",
    },
    {
        "title": "Berserk",
        "categories": [
            {"category": "Aventura"},
            {"category": "Ação"},
            {"category": "Romance"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11655/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11655/large.jpg",
        "original_title": "ベルセルク",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Millepensee, GEMBA",
        "sinopse": "Agora marcado para a morte e destinado a ser caçado por demônios até o dia de sua morte, Guts embarca em uma jornada para desafiar um destino tão horrível, enquanto ondas de feras o perseguem implacavelmente. Fortalecendo sua determinação, ele pega a lâmina monstruosa Matadora de Dragões e jura vingar-se do responsável, caçando o mesmo homem que ele uma vez olhou e considerou um amigo. Ao longo do caminho, ele encontra alguns aliados improváveis, como um pequeno elfo chamado Puck e Isidro, um jovem ladrão que procura aprender esgrima com o ex-mercenário. À medida que o grupo desorganizado se reúne lentamente depois de decidir se juntar a Guts em sua busca, eles enfrentarão um perigo incrível, diferente de tudo que já experimentaram antes.",
    },
    {
        "title": "Gangsta",
        "categories": [
            {"category": "Crime"},
            {"category": "Ação"},
            {"category": "Violência"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/8576/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/8576/large.jpg",
        "original_title": " Gangsta",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Manglobe",
        "sinopse": "Nicholas Brown e Worick Arcangelo, conhecidos na cidade de Ergastalum como os 'Handymen', são mercenários de aluguel que assumem trabalhos que ninguém mais pode fazer. Contratados por poderosos sindicatos da máfia e policiais, os Handymen precisam estar prontos e dispostos a qualquer coisa. Depois de completar a ordem de matar um cafetão local, os Faz-tudo adicionam Alex Benedetto – uma prostituta também designada para eliminação – às suas fileiras para protegê-la das forças que querem que ela saia da decrépita…",
    },
    {
        "title": "Pokemon",
        "categories": [
            {"category": "Aventura"},
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Fantasia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/486/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/486/large.jpg",
        "original_title": "Pokemon",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " TV Tokyo",
        "sinopse": "Os Pokémon são criaturas peculiares com uma vasta gama de habilidades e aparências diferentes; muitas pessoas, conhecidas como treinadores de Pokémon, os capturam e treinam, muitas vezes com a intenção de lutar contra os outros. O jovem Satoshi não apenas sonhava em se tornar um treinador Pokémon, mas também um 'Mestre Pokémon', e na chegada de seu 10º aniversário, ele finalmente tem a chance de tornar esse sonho realidade. Infelizmente para ele, todos os três Pokémon disponíveis para treinadores iniciantes já foram…",
    },
    {
        "title": "Tokyo Revengers",
        "categories": [
            {"category": "Crime"},
            {"category": "Ação"},
            {"category": "Shounen"},
            {"category": "Drama"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/43321/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/43321/large.jpg",
        "original_title": "Tokyo Revengers",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Liden Films",
        "sinopse": "Os Pokémon são criaturas peculiares com uma vasta gama de habilidades e aparências diferentes; muitas pessoas, conhecidas como treinadores de Pokémon, os capturam e treinam, muitas vezes com a intenção de lutar contra os outros. O jovem Satoshi não apenas sonhava em se tornar um treinador Pokémon, mas também um 'Mestre Pokémon', e na chegada de seu 10º aniversário, ele finalmente tem a chance de tornar esse sonho realidade. Infelizmente para ele, todos os três Pokémon disponíveis para treinadores iniciantes já foram…",
    },
    {
        "title": "Assassination Class Room ",
        "categories": [
            {"category": "Ficção"},
            {"category": "Ação"},
            {"category": "Comédia"},
            {"category": "Fantasia"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/manga/cover_images/19682/original.jpg",
        "image": "https://media.kitsu.io/manga/poster_images/19682/large.jpg",
        "original_title": "Ansatsu Kyoushitsu",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": "Lerche",
        "sinopse": "Os alunos da turma 3-E têm uma missão: matar seu professor antes da formatura. Ele já destruiu a lua e prometeu destruir a Terra se não puder ser morto dentro de um ano. Mas como essa classe de desajustados pode matar um monstro com tentáculos, capaz de atingir a velocidade Mach 20, que pode ser o melhor professor que qualquer um deles já teve?",
    },
    {
        "title": "Komi Can't Communicate",
        "categories": [{"category": "Shounen"}, {"category": "Comédia"}],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/manga/cover_images/37855/original.png",
        "image": "https://media.kitsu.io/manga/poster_images/37855/large.jpg",
        "original_title": "Komi-san wa, Comyushou desu.",
        "status": "On going",
        "launch_data": "2007-02-15",
        "studio": "Netflix",
        "sinopse": "É o primeiro dia de Shouko Komi na prestigiosa Itan Private High School, e ela já alcançou o status de Madonna da escola. Com longos cabelos negros e uma aparência alta e graciosa, ela chama a atenção de quem a encontra. Porém, há apenas um problema - apesar de sua popularidade, Shouko é terrível em se comunicar com os outros. Hitohito Tadano é um garoto comum do ensino médio. Com seu lema de vida de 'leia a situação e certifique-se de ficar longe...'",
    },
    {
        "title": "The Seven Deadly Sins",
        "categories": [
            {"category": "Shounen"},
            {"category": "Aventura"},
            {"category": "Ecchi"},
            {"category": "Ação"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/8699/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/8699/large.jpg",
        "original_title": "Nanatsu No Taisai",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " Imagens A-1",
        "sinopse": "Em um mundo semelhante à Idade Média européia, os temidos e reverenciados Cavaleiros Sagrados da Britannia usam magia imensamente poderosa para proteger a região da Britannia e seus reinos. No entanto, um pequeno subconjunto dos Cavaleiros supostamente traiu sua terra natal e virou suas lâminas contra seus companheiros na tentativa de derrubar o governante de Liones. Eles foram derrotados pelos Cavaleiros Sagrados, mas os rumores continuaram a persistir que esses cavaleiros lendários, chamados de 'Sete Mortais ...'",
    },
    {
        "title": "JoJo's Bizarre Adventure",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/7158/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/7158/large.jpg",
        "original_title": "JoJo no Kimyou na Bouken",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " David Production",
        "sinopse": "Em 1868, Dario Brando salva a vida de um nobre inglês, George Joestar. Ao acolher o filho de Dario, Dio, quando o menino fica órfão, George espera pagar a dívida que tem com seu salvador. No entanto, Dio, insatisfeito com sua posição na vida, aspira a tomar a casa Joestar para si. Empunhando uma máscara de pedra asteca com propriedades sobrenaturais, ele se propõe a destruir George e seu filho, Jonathan 'JoJo' Joestar, e desencadeia uma cadeia de eventos que continuará ecoando…",
    },
    {
        "title": "JoJo's Bizarre Adventure: Stardust Crusaders",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/8063/original.png",
        "image": "https://media.kitsu.io/anime/poster_images/8063/large.jpg",
        "original_title": "JoJo no Kimyou na Bouken: Stardust Crusaders",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " David Production",
        "sinopse": "Anos depois que um mal antigo foi resgatado das profundezas do mar, Joutarou Kuujou fica pacificamente dentro de uma cela de prisão japonesa. Ele não cometeu nenhum crime, mas exige que não seja libertado, acreditando estar possuído por um espírito maligno capaz de prejudicar aqueles ao seu redor. Preocupada com seu filho, Holly Kuujou pede a seu pai, Joseph Joestar, que convença Joutarou a deixar a prisão. Joseph informa ao neto que o “espírito maligno” é na verdade algo chamado “Stand”, o…",
    },
    {
        "title": "JoJo's Bizarre Adventure: Diamond is Unbreakable",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/11459/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/11459/large.jpg",
        "original_title": "JoJo no Kimyou na Bouken: Diamond wa Kudakenai",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " David Production",
        "sinopse": "O ano é 1999. Morioh, uma cidade normalmente calma e pacífica, tornou-se recentemente um foco de atividades estranhas. Joutarou Kuujou, agora um biólogo marinho, dirige-se à misteriosa cidade para conhecer Jousuke Higashikata. Enquanto os dois podem parecer estranhos no início, Jousuke é na verdade o filho ilegítimo do avô de Joutarou, Joseph Joestar. Quando eles se encontram, Joutarou percebe que ele pode ter mais em comum com Jousuke do que apenas uma relação de sangue. Juntamente com o …",
    },
    {
        "title": "JoJo's Bizarre Adventure: Golden Wind",
        "categories": [
            {"category": "Ação"},
            {"category": "Aventura"},
            {"category": "Shounen"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/cover_images/41410/original.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/41410/large.jpg",
        "original_title": "JoJo no Kimyou na Bouken: Ougon no Kaze",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " David Production",
        "sinopse": "Nápoles, 2001. Giorno Giovanna é um pequeno vigarista com um grande sonho - tornar-se um 'Gang-Star'. Nenhum ladrão comum, Giorno tem uma conexão com a notável linhagem Joestar e possui um Stand chamado Gold Experience. Seu sonho começa a se tornar realidade quando ele conhece Bruno Buccellati, um mafioso da gangue Passione e um colega usuário de Stand. Percebendo que eles compartilham ideais semelhantes e ambos discordam dos assuntos prejudiciais da gangue, Giorno revela seu objetivo de…",
    },
    {
        "title": "Parasyte -the maxim-",
        "categories": [
            {"category": "Ação"},
            {"category": "Terror"},
            {"category": "Ficção"},
        ],
        "average_rate": 0,
        "banner": "https://media.kitsu.io/anime/8147/cover_image/ddc8c50acee9f5b32f6dc1d236f354fc.jpg",
        "image": "https://media.kitsu.io/anime/poster_images/8147/large.jpg",
        "original_title": "Kiseijuu: Sei no Kakuritsu",
        "status": "Finished",
        "launch_data": "2007-02-15",
        "studio": " MADHOUSE",
        "sinopse": "De repente, eles chegaram: alienígenas parasitas que desceram sobre a Terra e rapidamente se infiltraram na humanidade, enterrando-se nos cérebros de alvos vulneráveis. Esses seres insaciáveis ​​adquirem o controle total de seu hospedeiro e são capazes de se transformar em uma variedade de formas para se alimentar de presas desavisadas. Shinichi Izumi, estudante do ensino médio de dezesseis anos, é vítima de um desses parasitas, mas não consegue dominar seu cérebro, acabando na mão direita. Incapaz de se mudar, o parasita, agora chamado Migi, não tem escolha a não ser confiar em Shinichi para permanecer vivo. Assim, a dupla é forçada a uma convivência desconfortável e deve se defender de parasitas hostis que esperam erradicar essa nova ameaça à sua espécie.",
    },
]

headers = {"Authorization": "Token 74220e05f62e23adb5a585010565e5ef2c77a188"}

for anime in animedb:
    print(anime["title"])
    response = requests.request(
        "POST", "http://localhost:8000/api/animes/", headers=headers, json=anime
    )
    print(response)
