# Generated by Django 4.0.6 on 2022-07-19 00:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=512)),
                ('studio', models.CharField(max_length=30)),
                ('banner', models.CharField(max_length=128)),
                ('original_title', models.CharField(max_length=50)),
                ('launch_data', models.DateField()),
                ('categories', models.ManyToManyField(to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='user',
            field=models.ManyToManyField(through='animes.Rate', to='users.user'),
        ),
    ]
