# Generated by Django 4.0.6 on 2022-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(default='not started', max_length=15),
        ),
    ]
