# Generated by Django 4.0.6 on 2022-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='sinopse',
            field=models.CharField(max_length=2000),
        ),
    ]
