# Generated by Django 4.0.6 on 2022-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0008_comment_anime_comments_comment_anime_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="original_title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
