# Generated by Django 4.0.6 on 2022-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0009_alter_anime_original_title_alter_anime_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="original_title",
            field=models.CharField(max_length=50),
        ),
    ]
