# Generated by Django 4.0.6 on 2022-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0010_alter_anime_original_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="original_title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
